/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp2019.interf;

import datab.dbconnect;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;



/**
 *
 * @author KAS2RI
 */
public class edit extends javax.swing.JFrame {
Connection ucon=null;
PreparedStatement upst=null;

    /**
     * Creates new form edit
     * 
     */
  
    public edit() {
        initComponents();
        ucon=dbconnect.connect();
        
    }
  
        
        
    
   
        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        ecid = new javax.swing.JLabel();
        edittp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editmail = new javax.swing.JTextField();
        editnic = new javax.swing.JTextField();
        editadd = new javax.swing.JTextField();
        editname = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        edityy = new javax.swing.JComboBox();
        editmm = new javax.swing.JComboBox();
        editdd = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jkab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 570, 160, 70);
        jPanel1.add(ecid);
        ecid.setBounds(460, 140, 40, 30);

        edittp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edittpKeyTyped(evt);
            }
        });
        jPanel1.add(edittp);
        edittp.setBounds(300, 390, 190, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 150, 180, 22);
        jPanel1.add(editmail);
        editmail.setBounds(300, 440, 240, 30);
        jPanel1.add(editnic);
        editnic.setBounds(300, 290, 170, 22);
        jPanel1.add(editadd);
        editadd.setBounds(300, 250, 290, 22);

        editname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editnameActionPerformed(evt);
            }
        });
        jPanel1.add(editname);
        editname.setBounds(300, 200, 280, 22);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 51));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(620, 570, 150, 60);

        edityy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));
        jPanel1.add(edityy);
        edityy.setBounds(285, 340, 80, 22);

        editmm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "january", "february", "march", "aprail", "may", "june", "july", "august", "september", "october", "november", "december" }));
        jPanel1.add(editmm);
        editmm.setBounds(410, 340, 110, 22);

        editdd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(editdd);
        editdd.setBounds(570, 340, 70, 22);

        jLabel9.setText("Email");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 440, 41, 16);

        jLabel8.setText("TP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 390, 15, 16);

        jLabel7.setText("D.O.B");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 340, 32, 16);

        jLabel6.setText("NIC");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 290, 30, 16);

        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 250, 46, 16);

        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 200, 50, 30);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 40, 320, 90);

        jkab.setIcon(new javax.swing.ImageIcon("C:\\Users\\KAS2RI\\Desktop\\ITP\\back.jpg")); // NOI18N
        jPanel1.add(jkab);
        jkab.setBounds(0, 0, 1023, 738);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String value0=ecid.getText();
        String value1=editname.getText();
        String value2=editadd.getText();
        String value3=editnic.getText();
        String value4=edityy.getSelectedItem().toString();
        String value5=editmm.getSelectedItem().toString();
        String value6=editdd.getSelectedItem().toString();
        String value7=edittp.getText();
        String value8=editmail.getText();
       
        if(valid()){
            
             try
             
             {
                 String sq="UPDATE `customer` SET `cid`='"+value0+"',`name`='"+value1+"',`address`='"+value2+"',`nic`='"+value3+"', `year`='"+value4+"',`month`='"+value5+"',`date`='"+value6+"',`tp`='"+value7+"',`email`='"+value8+"' WHERE `cid` = '"+value0+"'";
                 upst=ucon.prepareStatement(sq);
                 upst.execute();
             }

             catch(Exception e)
             {

            }
        JOptionPane.showMessageDialog(null,"Upadte Succesfull");
        ecid.getText();
        editname.setText("");
        editadd.setText("");
        editnic.setText("");
        edityy.setSelectedItem(null);
        editmm.setSelectedItem(null);
        editdd.setSelectedItem(null);
        edittp.setText("");
        editmail.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        report re =new report();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void edittpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edittpKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
         evt.consume();
        }
    }//GEN-LAST:event_edittpKeyTyped
public boolean valid(){
    
if(editname.getText().equals("")|| editadd.getText().equals("")|| editnic.getText().equals("")|| edittp.getText().equals("")||editmail.getText().equals(""))
{
    JOptionPane.showMessageDialog(null, "Field Can not be ", "Error", JOptionPane.ERROR_MESSAGE);
    return false;

    

    
}
    else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", editmail.getText()))) 
{
    JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
    return false;
 }
else 
{
    return true;
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new edit().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel ecid;
    public static javax.swing.JTextField editadd;
    public static javax.swing.JComboBox editdd;
    public static javax.swing.JTextField editmail;
    public static javax.swing.JComboBox editmm;
    public static javax.swing.JTextField editname;
    public static javax.swing.JTextField editnic;
    public static javax.swing.JTextField edittp;
    public static javax.swing.JComboBox edityy;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jkab;
    // End of variables declaration//GEN-END:variables
}
