/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp2019.interf;
import datab.dbconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KAS2RI
 */
public class report extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst = null;
ResultSet rs =null;

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        con=dbconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        report = new javax.swing.JDesktopPane();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mmm = new javax.swing.JLabel();
        yyyy = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dddd = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rcid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton5.setText("Main");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 10, 100, 50);

        jButton4.setText("Show table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(869, 160, 110, 25);

        javax.swing.GroupLayout reportLayout = new javax.swing.GroupLayout(report);
        report.setLayout(reportLayout);
        reportLayout.setHorizontalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        reportLayout.setVerticalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(report);
        report.setBounds(390, 210, 600, 440);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 51));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(220, 470, 150, 60);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 0));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 470, 150, 60);
        jPanel1.add(email);
        email.setBounds(80, 410, 250, 20);

        jLabel9.setText("Email");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 410, 41, 16);
        jPanel1.add(tp);
        tp.setBounds(90, 370, 170, 20);

        jLabel8.setText("TP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 370, 15, 16);
        jPanel1.add(mmm);
        mmm.setBounds(160, 330, 60, 20);
        jPanel1.add(yyyy);
        yyyy.setBounds(90, 330, 40, 20);

        jLabel7.setText("D.O.B");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 330, 32, 16);
        jPanel1.add(dddd);
        dddd.setBounds(130, 330, 40, 20);
        jPanel1.add(nic);
        nic.setBounds(100, 290, 190, 20);

        jLabel6.setText("NIC");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 290, 30, 16);
        jPanel1.add(address);
        address.setBounds(100, 250, 310, 20);

        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 250, 46, 16);

        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 50, 30);
        jPanel1.add(name);
        name.setBounds(100, 210, 300, 20);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 150, 79, 25);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 40, 320, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter Customer ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 150, 180, 22);

        rcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcidActionPerformed(evt);
            }
        });
        jPanel1.add(rcid);
        rcid.setBounds(220, 150, 110, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\KAS2RI\\Desktop\\ITP\\back.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1023, 738);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void cleardata(){
            rcid.setText(null);
            name.setText(null);
            address.setText(null);
            nic.setText(null);
            yyyy.setText(null);
            mmm.setText(null);
            dddd.setText(null);
            tp.setText(null);
            email.setText(null);
    }
    private void rcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=rcid.getText();
          try {
        String sql ="SELECT * FROM customer WHERE cid=? ";
  
        pst=con.prepareStatement(sql);
        pst.setInt(1,Integer.parseInt(rcid.getText()));
        rs =pst.executeQuery();
        if(rs.next())
        {
            name.setText(rs.getString("name"));
            address.setText(rs.getString("address"));
            nic.setText(rs.getString("nic"));
            yyyy.setText(rs.getString("year"));
            mmm.setText(rs.getString("month"));
            dddd.setText(rs.getString("date"));
            tp.setText(rs.getString("tp"));
            email.setText(rs.getString("email"));
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "record not found");
            cleardata();
        }
       
        
    } catch (Exception ex) {
        System.out.println(ex);
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        edit ed=new edit();
       
            edit.ecid.setText(rcid.getText());
            edit.editname.setText(name.getText());
            edit.editadd.setText(address.getText());
            edit.editnic.setText(nic.getText());
            edit.edityy.setSelectedItem(yyyy.getText());
            edit.editmm.setSelectedItem(mmm.getText());
            edit.editdd.setSelectedItem(dddd.getText());
            edit.edittp.setText(tp.getText());
            edit.editmail.setText(email.getText());
           
        
    
        
        
       ed.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    int x=JOptionPane.showConfirmDialog(null,"Do you want to DELETE this acount?");
    if(x==0)
    {
        String id=rcid.getText();
        String sq="DELETE from customer where cid='"+id+"'";
        try {
            pst=con.prepareStatement(sq);
            pst.execute();
            
        } catch (SQLException ex) {
            
        }
        cleardata();
      
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cus_report re1 = new cus_report();
        report.add(re1).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Signup sig = new Signup();
        sig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel dddd;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mmm;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nic;
    private javax.swing.JTextField rcid;
    private javax.swing.JDesktopPane report;
    private javax.swing.JLabel tp;
    private javax.swing.JLabel yyyy;
    // End of variables declaration//GEN-END:variables
}
